

spring:
  application:
    name: payment-service

  config:
    import:
      "optional:configserver:http://localhost:8088"
  jpa:
    show_sql: true
    defer-datasource-initialization: false
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
        hbm2ddl:
          auto: "update"

  datasource:
    url: "jdbc:mysql://localhost:5000/payment_service"
    username: "root"
    password: "123456"


stripe:
  apiKey: "sk_test_51NIcknISk3dUEhPomOXn9gbLUNMJG0ORSHEvDWHiHB0CvQEP7DXOzjTrxV127nAtfav5XyLceYEE14CAQ7rb27SE00avdL8KCs"
